### ISSUE TITLE
Link to examples in README.md doesn't work

### ISSUE THREAD

**Issue by sstarr** [vizicities/vizicities#133]
Hello,

This link to the examples from the README isn't working:

* Play with the [interactive ViziCities examples](http://vizicities.com/examples)

It just goes to a page which says "Not Found".

**Comment by robhawkes** [comment]
Thanks for pointing this out, I've removed the link for now although some examples can be found here: https://github.com/vizicities/vizicities/tree/0.2.0/examples (and accessed via rawgit, eg: https://rawgit.com/vizicities/vizicities/0.2.0/examples/basic-example/index.html).
