### ISSUE TITLE
Basic demo doesn't work

### ISSUE THREAD

**Issue by chrisabrams** [vizicities/vizicities#149]
I've tried following the Github, the JSBin link, and I can't get any of them to work. I get errors about three.js missing, underscore missing, etc. I've tried resolving this myself, but then I get errors about `THREE.MOUSE.LEFT` and such being undefined. Any help on what I'm missing?

The JSBin demo's error is:

     Uncaught TypeError: Cannot read property 'querySelector' of undefined

**Comment by robhawkes** [comment]
Aha! My mistake, it looks like I forgot to update the JSBin when the control system changed. I've put a fixed version here and updated the readme: http://jsbin.com/qaqogo/2/edit?html,js,output

Let me know if that doesn't work for you.

**Comment by chrisabrams** [comment]
Yep that works - thanks for the update!

**Comment by robhawkes** [comment]
Awesome, I'm glad it's all working ok now.
